#!/bin/bash

# Installation script for daily-commits
# This script installs daily-commits globally on your system

set -e  # Exit on error

COLOR_GREEN='\033[0;32m'
COLOR_BLUE='\033[0;34m'
COLOR_YELLOW='\033[1;33m'
COLOR_RED='\033[0;31m'
COLOR_RESET='\033[0m'

INSTALL_DIR="/usr/local/bin"
COMMAND_NAME="daily-commits"
CONFIG_DIR="${HOME}/.config/daily-git-commits"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo ""
echo -e "${COLOR_BLUE}╔═══════════════════════════════════════════════════════╗${COLOR_RESET}"
echo -e "${COLOR_BLUE}║                                                       ║${COLOR_RESET}"
echo -e "${COLOR_BLUE}║           📅  daily-commits installer  ✨             ║${COLOR_RESET}"
echo -e "${COLOR_BLUE}║                                                       ║${COLOR_RESET}"
echo -e "${COLOR_BLUE}╚═══════════════════════════════════════════════════════╝${COLOR_RESET}"
echo ""

# Check if we need sudo
if [[ ! -w "$INSTALL_DIR" ]]; then
  echo -e "${COLOR_YELLOW}⚠️  Installing to ${INSTALL_DIR} requires elevated privileges${COLOR_RESET}"
  echo -e "   You may be prompted for your password...\n"
  USE_SUDO="sudo"
else
  USE_SUDO=""
fi

# Check if already installed
if [[ -f "${INSTALL_DIR}/${COMMAND_NAME}" ]]; then
  echo -e "${COLOR_YELLOW}⚠️  ${COMMAND_NAME} is already installed${COLOR_RESET}"
  read -p "   Do you want to reinstall/update it? (y/N) " -n 1 -r
  echo
  if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo -e "\n${COLOR_BLUE}Installation cancelled.${COLOR_RESET}\n"
    exit 0
  fi
  echo ""
fi

# Install the script
echo -e "${COLOR_BLUE}📦 Installing ${COMMAND_NAME}...${COLOR_RESET}"
$USE_SUDO cp "${SCRIPT_DIR}/src/daily-commits" "${INSTALL_DIR}/${COMMAND_NAME}"
$USE_SUDO chmod +x "${INSTALL_DIR}/${COMMAND_NAME}"
echo -e "${COLOR_GREEN}✓ Installed to ${INSTALL_DIR}/${COMMAND_NAME}${COLOR_RESET}"
echo ""

# Setup configuration
echo -e "${COLOR_BLUE}⚙️  Setting up configuration...${COLOR_RESET}"

if [[ ! -d "$CONFIG_DIR" ]]; then
  mkdir -p "$CONFIG_DIR"
  echo -e "${COLOR_GREEN}✓ Created config directory: ${CONFIG_DIR}${COLOR_RESET}"
fi

if [[ -f "${CONFIG_DIR}/.env" ]]; then
  echo -e "${COLOR_YELLOW}⚠️  Configuration already exists at: ${CONFIG_DIR}/.env${COLOR_RESET}"
  echo -e "   Keeping your existing configuration."
  SKIP_CONFIG=true
else
  echo ""
  echo -e "${COLOR_BLUE}Let's configure daily-commits!${COLOR_RESET}"
  echo ""
  
  # Get git author name with default from git config
  DEFAULT_AUTHOR=$(git config --global user.name 2>/dev/null || echo "")
  if [[ -n "$DEFAULT_AUTHOR" ]]; then
    read -p "$(echo -e ${COLOR_YELLOW})Your git author name [${DEFAULT_AUTHOR}]: $(echo -e ${COLOR_RESET})" AUTHOR
    AUTHOR="${AUTHOR:-$DEFAULT_AUTHOR}"
  else
    read -p "$(echo -e ${COLOR_YELLOW})Your git author name: $(echo -e ${COLOR_RESET})" AUTHOR
    while [[ -z "$AUTHOR" ]]; do
      echo -e "${COLOR_RED}Author name is required!${COLOR_RESET}"
      read -p "$(echo -e ${COLOR_YELLOW})Your git author name: $(echo -e ${COLOR_RESET})" AUTHOR
    done
  fi
  
  # Get projects directory
  read -p "$(echo -e ${COLOR_YELLOW})Path to your projects directory: $(echo -e ${COLOR_RESET})" PROJECTS_DIR
  while [[ -z "$PROJECTS_DIR" ]]; do
    echo -e "${COLOR_RED}Projects directory is required!${COLOR_RESET}"
    read -p "$(echo -e ${COLOR_YELLOW})Path to your projects directory: $(echo -e ${COLOR_RESET})" PROJECTS_DIR
  done
  
  # Expand ~ to home directory if used
  PROJECTS_DIR="${PROJECTS_DIR/#\~/$HOME}"
  
  # Validate directory exists
  if [[ ! -d "$PROJECTS_DIR" ]]; then
    echo -e "${COLOR_YELLOW}⚠️  Warning: Directory does not exist: ${PROJECTS_DIR}${COLOR_RESET}"
    read -p "$(echo -e ${COLOR_YELLOW})Create it now? (y/N) $(echo -e ${COLOR_RESET})" -n 1 -r
    echo ""
    if [[ $REPLY =~ ^[Yy]$ ]]; then
      mkdir -p "$PROJECTS_DIR"
      echo -e "${COLOR_GREEN}✓ Created directory${COLOR_RESET}"
    else
      echo -e "${COLOR_BLUE}ℹ️  Continuing anyway. Make sure to create it before using daily-commits.${COLOR_RESET}"
    fi
  fi
  
  # Get max depth (optional)
  read -p "$(echo -e ${COLOR_YELLOW})Maximum search depth for git repos [3]: $(echo -e ${COLOR_RESET})" MAXDEPTH
  MAXDEPTH="${MAXDEPTH:-3}"
  
  # Validate maxdepth is a number
  if ! [[ "$MAXDEPTH" =~ ^[0-9]+$ ]]; then
    echo -e "${COLOR_YELLOW}⚠️  Invalid depth, using default: 3${COLOR_RESET}"
    MAXDEPTH=3
  fi
  
  # Write configuration file
  cat > "${CONFIG_DIR}/.env" << EOF
# Daily Git Commits Configuration
# Generated by installer on $(date)

# Your git author name (should match your git config user.name)
AUTHOR="${AUTHOR}"

# Root directory where your git projects are located
LOCAL_PROJECTS_DIRECTORY_ROOT="${PROJECTS_DIR}"

# Maximum depth to search for git repositories (default: 3)
# Increase if your projects are nested deeper
MAXDEPTH=${MAXDEPTH}
EOF
  
  echo ""
  echo -e "${COLOR_GREEN}✓ Configuration saved to ${CONFIG_DIR}/.env${COLOR_RESET}"
fi

echo ""
echo -e "${COLOR_GREEN}╔═══════════════════════════════════════════════════════╗${COLOR_RESET}"
echo -e "${COLOR_GREEN}║                                                       ║${COLOR_RESET}"
echo -e "${COLOR_GREEN}║           ✅  Installation complete! 🎉               ║${COLOR_RESET}"
echo -e "${COLOR_GREEN}║                                                       ║${COLOR_RESET}"
echo -e "${COLOR_GREEN}╚═══════════════════════════════════════════════════════╝${COLOR_RESET}"
echo ""

if [[ -z "$SKIP_CONFIG" ]]; then
  echo -e "${COLOR_BLUE}You're all set! Try it out:${COLOR_RESET}"
  echo -e "  ${COLOR_GREEN}${COMMAND_NAME}${COLOR_RESET}"
else
  echo -e "${COLOR_BLUE}Your existing configuration was preserved.${COLOR_RESET}"
  echo -e "  Config file: ${COLOR_YELLOW}${CONFIG_DIR}/.env${COLOR_RESET}"
fi

echo ""
echo -e "${COLOR_BLUE}💡 Note:${COLOR_RESET} If the command isn't found, run: ${COLOR_GREEN}hash -r${COLOR_RESET}"
echo -e "   (This refreshes your shell's command cache)"

echo ""
echo -e "${COLOR_BLUE}Usage Examples:${COLOR_RESET}"
echo -e "  ${COMMAND_NAME}              # Today's commits"
echo -e "  ${COMMAND_NAME} yd           # Yesterday's commits"
echo -e "  ${COMMAND_NAME} w            # Last 7 days"
echo -e "  ${COMMAND_NAME} 3d           # Last 3 days"
echo -e "  ${COMMAND_NAME} 2025-11-01   # Specific date"
echo ""
echo -e "${COLOR_BLUE}To reconfigure:${COLOR_RESET}"
echo -e "  Edit: ${COLOR_YELLOW}${CONFIG_DIR}/.env${COLOR_RESET}"
echo ""
echo -e "${COLOR_BLUE}To uninstall:${COLOR_RESET}"
echo -e "  cd ${SCRIPT_DIR}"
echo -e "  ./uninstall.sh"
echo ""

